[package]
name = "KOX-NFT"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
uuid = { version = "1.18.1", features = ["v4"] }
